version: '3.7'

services:
  book-api:
    container_name: book-api
    image: node:14-alpine
    working_dir: /app/demo
    command: "npm run start:book"
    environment:
      PORT: 3000
    volumes:
      - "./:/app/demo"  
    networks:
      - kong_network
    ports:
      - 3000:3000

  validate-api:
    container_name: validate-api
    image: node:14-alpine
    working_dir: /app/demo
    command: "npm run start:validate"
    environment:
      PORT: 8080
    volumes:
      - "./:/app/demo"
    networks:
      - kong_network
    ports:
      - 8080:8080

networks:
  kong_network:
    external: true
